apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app   # The name of your deployment, can be customized.
spec:
  replicas: 3   # Number of replica pods to maintain. Adjust as needed.
  selector:
    matchLabels:
      app: my-nodejs-app   # Label to select pods for this deployment.
  template:
    metadata:
      labels:
        app: my-nodejs-app   # Label to identify pods created by this template.
    spec:
      containers:
      - name: my-nodejs-app
        image: rielam/mynodejsapp:latest   # Docker image to use for the container.
        ports:
        - containerPort: 3000   # Port exposed by the container (your app should listen on this port).
        resources:
          limits:
            memory: 2048Mi
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app
  namespace: default
spec:
  selector:
    app: my-nodejs-app
  type: NodePort
  ports:
  - name: http
    targetPort: 3000
    port: 80