apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app   # The name of your deployment, can be customized.
spec:
  replicas: 3   # Number of replica pods to maintain. Adjust as needed.
  selector:
    matchLabels:
      app: my-nodejs-app   # Label to select pods for this deployment.
  template:
    metadata:
      labels:
        app: my-nodejs-app   # Label to identify pods created by this template.
    spec:
      containers:
      - name: my-nodejs-app
        image: your-docker-username/my-nodejs-app:v1.0.0   # Docker image to use for the container.
        ports:
        - containerPort: 3000   # Port exposed by the container (your app should listen on this port).