# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main   # Trigger the workflow when code is pushed to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest   # Use the latest version of Ubuntu as the runner.
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2   # Use the 'actions/checkout' action to fetch your code.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker buildx create --use
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t rielam/mynodejsapp:latest \
          -f Dockerfile \
          .

        docker push rielam/mynodejsapp:latest