# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main   # Trigger the workflow when code is pushed to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest   # Use the latest version of Ubuntu as the runner.
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2   # Use the 'actions/checkout' action to fetch your code.

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          rielam/mynodejsapp:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}