# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t rielam/mynodejsapp:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push rielam/mynodejsapp:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Try the cluster !
        run: kubectl get pods -A

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml  
